### ISSUE TITLE
handAll 函数那里判断有误

### ISSUE THREAD

**Issue by Jasminehyz** [ASkyBig/vue-shopping-cart#1]
handAll函数那里应该是：
`chooseAll:function(){
                var status=this.isCheckedAll();
                status=status?1:0;
                for(var i=0;i<this.list.length;i++){
                    this.list[i].status=status;
                }
            }`
也就是status=statues?1:0的判断你写反了，哈哈

**Comment by ASkyBig** [comment]
> handAll函数那里应该是：
> `chooseAll:function(){ var status=this.isCheckedAll(); status=status?1:0; for(var i=0;i<this.list.length;i++){ this.list[i].status=status; } }`
> 也就是status=statues?1:0的判断你写反了，哈哈

写反了吗？如果已经全选了就点击取消全选，否则全选。没错吧？@huangyuanzhen
